# **Assignment on Numpy Module **

# 1.	Array Creation
o	Create a 1D array of numbers from 10 to 50.

o	Create a 3x3 array of random numbers between 0 and 1.


In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10, 51)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
arr2 = np.random.rand(3, 3)
print(arr2)

[[0.78654898 0.50810457 0.43747158]
 [0.78469031 0.97465482 0.01563483]
 [0.5575864  0.68054124 0.43425649]]


# 2.	Array Attributes
o	Find the shape, size, and data type of the array you created in the previous task.



In [5]:
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:",arr2.dtype)

Shape: (3, 3)
Size: 9
Data Type: float64


# 3.	Basic Operations
o	Add 5 to every element of a 1D array.

o	Multiply two 2D arrays element-wise.


In [7]:
arr3= np.array([1, 2, 3, 4, 5])
sum= arr3 + 5
print("Adding 5 to evry element in the array:",sum)

Adding 5 to evry element in the array: [ 6  7  8  9 10]


In [8]:
arr1 = np.array([[10, 20], [30, 40]])
arr2 = np.array([[50, 60], [70, 80]])

mul= arr1 * arr2
print("Element-wise multiplication of arrays:\n",mul)


Element-wise multiplication of arrays:
 [[ 500 1200]
 [2100 3200]]


# 4.	Indexing and Slicing
o	Create a 5x5 array of integers from 1 to 25. Extract:

	The first row.

	The last column.

	A subarray of the first three rows and first two columns.

In [9]:
array = np.arange(1, 26).reshape(5, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
first_row = array[0, :]
print("First Row:", first_row)

First Row: [1 2 3 4 5]


In [12]:
last_column = array[:, -1]
print("Last Column:", last_column)

Last Column: [ 5 10 15 20 25]


In [14]:
array2 = array[:3, :2]
print("Subarray (First 3 rows and 2 columns):\n",array2)

Subarray (First 3 rows and 2 columns):
 [[ 1  2]
 [ 6  7]
 [11 12]]


# 5.	Aggregation
o	Create a 10-element array of random integers between 1 and 100. Find:

	The maximum value.

	The minimum value.

	The mean and standard deviation.


In [16]:
rand_arr= np.random.randint(1, 101, 10)
print(rand_arr)
print("Maximum value:",rand_arr.max())
print("Minimum value:",rand_arr.min())
print("Mean value:",rand_arr.mean())
print("Standard deviation:",rand_arr.std())

[66 13 24 55 85 38 21 75 37 17]
Maximum value: 85
Minimum value: 13
Mean value: 43.1
Standard deviation: 24.37806390999909


# 6.	Reshaping
o	Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix


In [17]:
reshape_arr= np.arange(1, 13).reshape(3, 4)
print(reshape_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 7.	Broadcasting
o	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [18]:
import numpy as np
matrix = np.ones((3, 3))
arr = np.array([1, 2, 3])
res_matrix= matrix + arr
print("After Broadcasting:\n",res_matrix)


After Broadcasting:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


# 8.	Filtering
o	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.


In [23]:
arr= np.random.randint(1,51,20)
print(arr)
filtered_arr= arr[arr % 5 == 0]
print("Elements divisible by 5:",filtered_arr)

[40  6 46  5 10 42 22 41 33 25 20 36  5  1 19 28 16  6 42 24]
Elements divisible by 5: [40  5 10 25 20  5]


# 9.	Matrix Multiplication
o	Create two 2x2 matrices and perform matrix multiplication.


In [25]:
matrix_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                    [7, 8, 9]])

matrix_2 = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])
mat_mul=np.dot(matrix_1,matrix_2)
print(mat_mul)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# 10.	Advanced Indexing
o	Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [27]:
import numpy as np
arr= np.arange(1, 17).reshape(4, 4)
diagonal_ele = arr.diagonal()
print("Diagonal Elements:", diagonal_ele)


Diagonal Elements: [ 1  6 11 16]
